import type { VercelRequest, VercelResponse } from '@vercel/node';

const UUID = /^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i;
const UPSTREAM = 'https://api.xross-stars.com/v1/decks/';
const MAX_BYTES = 1_500_000, TIMEOUT_MS = 7_000, CACHE_MS = 600_000, RATE_WINDOW_MS = 60_000, RATE_MAX = 30;
type OfficialCard = { id:number; name:string; display_card_number:string; image_url?:string; is_ace?:boolean; card_type?:{internal_id:string} };
type OfficialDeck = { leader:OfficialCard[]; deck:OfficialCard[]; tactics:OfficialCard[] };
type Card = { id:string; name:string; cardType:'leader'|'main'|'tactics'; imageUrl?:string; isAce:boolean };
type Payload = { officialDeckCode:string; leaders:Card[]; mainDeck:(Card & {count:number})[]; tactics:Card[]; aceSummary:{cardId:string;name:string;count:number}[] };
const cache = new Map<string,{expires:number;value:Payload}>(), visitors = new Map<string,{started:number;count:number}>();
function toCard(card:OfficialCard, fallback:Card['cardType']):Card { const kind=card.card_type?.internal_id; return {id:card.display_card_number?.split(' ')[0]||String(card.id),name:card.name,cardType:kind==='leader'?'leader':kind==='tactics'?'tactics':fallback,imageUrl:card.image_url,isAce:Boolean(card.is_ace)}; }
/** Verified official API: GET /v1/decks/{uuid}; no authentication, cookies, or extra headers. */
async function fetchOfficialDeck(code:string):Promise<Payload> { const controller=new AbortController(), timer=setTimeout(()=>controller.abort(),TIMEOUT_MS); try { const response=await fetch(`${UPSTREAM}${code}`,{method:'GET',headers:{Accept:'application/json'},signal:controller.signal}); if(!response.ok) throw new Error(`UPSTREAM_${response.status}`); if(Number(response.headers.get('content-length')||'0')>MAX_BYTES) throw new Error('UPSTREAM_TOO_LARGE'); const text=await response.text(); if(new TextEncoder().encode(text).byteLength>MAX_BYTES) throw new Error('UPSTREAM_TOO_LARGE'); const raw=JSON.parse(text) as OfficialDeck; if(!Array.isArray(raw.leader)||!Array.isArray(raw.deck)||!Array.isArray(raw.tactics)) throw new Error('INVALID_SCHEMA'); const tally=new Map<string,Card & {count:number}>(); for(const rawCard of raw.deck){const card=toCard(rawCard,'main'),old=tally.get(card.id);if(old)old.count++;else tally.set(card.id,{...card,count:1})} const mainDeck=[...tally.values()]; return {officialDeckCode:code,leaders:raw.leader.map(x=>toCard(x,'leader')),mainDeck,tactics:raw.tactics.map(x=>toCard(x,'tactics')),aceSummary:mainDeck.filter(x=>x.isAce).map(x=>({cardId:x.id,name:x.name,count:x.count}))}; } finally {clearTimeout(timer)} }
export default async function handler(req:VercelRequest,res:VercelResponse) { if(req.method!=='GET') return res.status(405).json({error:'METHOD_NOT_ALLOWED'}); const code=Array.isArray(req.query.deckCode)?'':req.query.deckCode||''; if(!UUID.test(code)) return res.status(400).json({error:'INVALID_DECK_CODE'}); const ip=req.headers['x-forwarded-for']?.toString().split(',')[0]||req.socket.remoteAddress||'unknown',now=Date.now(),visitor=visitors.get(ip); if(!visitor||now-visitor.started>RATE_WINDOW_MS) visitors.set(ip,{started:now,count:1}); else {visitor.count++;if(visitor.count>RATE_MAX)return res.status(429).json({error:'RATE_LIMITED'})} const hit=cache.get(code); if(hit&&hit.expires>now)return res.setHeader('Cache-Control','public, s-maxage=600, stale-while-revalidate=3600').status(200).json(hit.value); try {const value=await fetchOfficialDeck(code);cache.set(code,{expires:now+CACHE_MS,value});return res.setHeader('Cache-Control','public, s-maxage=600, stale-while-revalidate=3600').status(200).json(value)}catch(error){const message=error instanceof Error?error.message:'UNKNOWN',status=message==='UPSTREAM_404'?404:message==='UPSTREAM_TOO_LARGE'||message==='INVALID_SCHEMA'?502:504;return res.status(status).json({error:'OFFICIAL_DECK_UNAVAILABLE'})} }
